#goal
int32 objectType
bool servoing

#Constants for object types
int32 startGate=0
int32 pole=1
---
#result
bool stoppedOk
bool found
bool poleDone
---
#feedback
int32[] center
int32 width
int32 height
bool found

#Pose used to pass back fix information
#If fix type is direction, the point component is a direction vector
#If fix type is position, point component is the position in camera space (add header for frame id?)
#if fix type is pose, point and quaternion are pose in camera space
#quaternion is only valid for pose fix type
geometry_msgs/Pose targetPose
