#goal
int32 objectType

#Constants for object types
int32 startGate=0
int32 pole=1
---
#result
bool stoppedOk
bool found
bool poleDone
---
#feedback
Header header
int32 fixType

#constants for fix types
int32 center=0
int32 width=1

#Pose used to pass back fix information
#If fix type is direction, the point component is a direction vector
#If fix type is position, point component is the position in camera space (add header for frame id?)
#if fix type is pose, point and quaternion are pose in camera space
#quaternion is only valid for pose fix type
geometry_msgs/Pose targetPose
